version: "3.9"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    restart: always

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    restart: always
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
  

  user-service:
    build: ./user-service
    container_name: user-container
    ports:
      - "3000:3000"
    depends_on:
      - kafka


  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "3001:3001"
    depends_on:
      - kafka
  

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "3004:3004"
    depends_on:
      - kafka

  cart-service:
    build: ./cart-service
    container_name: cart-service
    ports:
      - "3003:3003"
    depends_on:
      - kafka

  auth-service:
    build: ./auth-service
    container_name: auth-service
    depends_on:
      - kafka